export const TIMEZONE_OPTIONS = [
  // Africa
  {
    label: 'Cairo',
    region: 'Egypt',
    timezone: 'Africa/Cairo',
    latitude: 30.0444,
    longitude: 31.2357,
  },
  {
    label: 'Cape Town',
    region: 'South Africa',
    timezone: 'Africa/Johannesburg',
    latitude: -33.9249,
    longitude: 18.4241,
  },
  {
    label: 'Casablanca',
    region: 'Morocco',
    timezone: 'Africa/Casablanca',
    latitude: 33.5731,
    longitude: -7.5898,
  },
  {
    label: 'Lagos',
    region: 'Nigeria',
    timezone: 'Africa/Lagos',
    latitude: 6.5244,
    longitude: 3.3792,
  },
  {
    label: 'Nairobi',
    region: 'Kenya',
    timezone: 'Africa/Nairobi',
    latitude: -1.286389,
    longitude: 36.817223,
  },

  // Asia
  {
    label: 'Bangkok',
    region: 'Thailand',
    timezone: 'Asia/Bangkok',
    latitude: 13.7563,
    longitude: 100.5018,
  },
  {
    label: 'Beijing',
    region: 'China',
    timezone: 'Asia/Shanghai',
    latitude: 39.9042,
    longitude: 116.4074,
  },
  {
    label: 'Dubai',
    region: 'UAE',
    timezone: 'Asia/Dubai',
    latitude: 25.276987,
    longitude: 55.296249,
  },
  {
    label: 'Jakarta',
    region: 'Indonesia',
    timezone: 'Asia/Jakarta',
    latitude: -6.2088,
    longitude: 106.8456,
  },
  {
    label: 'Mumbai',
    region: 'India',
    timezone: 'Asia/Kolkata',
    latitude: 19.076,
    longitude: 72.8777,
  },
  {
    label: 'Seoul',
    region: 'South Korea',
    timezone: 'Asia/Seoul',
    latitude: 37.5665,
    longitude: 126.978,
  },
  {
    label: 'Singapore',
    region: 'Singapore',
    timezone: 'Asia/Singapore',
    latitude: 1.3521,
    longitude: 103.8198,
  },
  {
    label: 'Taipei',
    region: 'Taiwan',
    timezone: 'Asia/Taipei',
    latitude: 25.033,
    longitude: 121.565,
  },
  {
    label: 'Tokyo',
    region: 'Japan',
    timezone: 'Asia/Tokyo',
    latitude: 35.6895,
    longitude: 139.6917,
  },

  // Australia & Pacific
  {
    label: 'Auckland',
    region: 'New Zealand',
    timezone: 'Pacific/Auckland',
    latitude: -36.8485,
    longitude: 174.7633,
  },
  {
    label: 'Brisbane',
    region: 'Australia',
    timezone: 'Australia/Brisbane',
    latitude: -27.4698,
    longitude: 153.0251,
  },
  {
    label: 'Melbourne',
    region: 'Australia',
    timezone: 'Australia/Melbourne',
    latitude: -37.8136,
    longitude: 144.9631,
  },
  {
    label: 'Perth',
    region: 'Australia',
    timezone: 'Australia/Perth',
    latitude: -31.9505,
    longitude: 115.8605,
  },
  {
    label: 'Sydney',
    region: 'Australia',
    timezone: 'Australia/Sydney',
    latitude: -33.8688,
    longitude: 151.2093,
  },

  // Europe
  {
    label: 'Athens',
    region: 'Greece',
    timezone: 'Europe/Athens',
    latitude: 37.9838,
    longitude: 23.7275,
  },
  {
    label: 'Berlin',
    region: 'Germany',
    timezone: 'Europe/Berlin',
    latitude: 52.52,
    longitude: 13.405,
  },
  {
    label: 'Istanbul',
    region: 'Turkey',
    timezone: 'Europe/Istanbul',
    latitude: 41.0082,
    longitude: 28.9784,
  },
  {
    label: 'London',
    region: 'United Kingdom',
    timezone: 'Europe/London',
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    label: 'Madrid',
    region: 'Spain',
    timezone: 'Europe/Madrid',
    latitude: 40.4168,
    longitude: -3.7038,
  },
  {
    label: 'Moscow',
    region: 'Russia',
    timezone: 'Europe/Moscow',
    latitude: 55.7558,
    longitude: 37.6173,
  },
  {
    label: 'Paris',
    region: 'France',
    timezone: 'Europe/Paris',
    latitude: 48.8566,
    longitude: 2.3522,
  },
  {
    label: 'Rome',
    region: 'Italy',
    timezone: 'Europe/Rome',
    latitude: 41.9028,
    longitude: 12.4964,
  },

  // North America
  {
    label: 'Chicago',
    region: 'USA',
    timezone: 'America/Chicago',
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    label: 'Las Vegas',
    region: 'USA',
    timezone: 'America/Los_Angeles',
    latitude: 36.1699,
    longitude: -115.1398,
  },
  {
    label: 'Los Angeles',
    region: 'USA',
    timezone: 'America/Los_Angeles',
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    label: 'Mexico City',
    region: 'Mexico',
    timezone: 'America/Mexico_City',
    latitude: 19.4326,
    longitude: -99.1332,
  },
  {
    label: 'New York',
    region: 'USA',
    timezone: 'America/New_York',
    latitude: 40.7128,
    longitude: -74.006,
  },
  {
    label: 'Toronto',
    region: 'Canada',
    timezone: 'America/Toronto',
    latitude: 43.65107,
    longitude: -79.347015,
  },
  {
    label: 'Vancouver',
    region: 'Canada',
    timezone: 'America/Vancouver',
    latitude: 49.2827,
    longitude: -123.1207,
  },

  // South America
  {
    label: 'Bogotá',
    region: 'Colombia',
    timezone: 'America/Bogota',
    latitude: 4.711,
    longitude: -74.0721,
  },
  {
    label: 'Buenos Aires',
    region: 'Argentina',
    timezone: 'America/Argentina/Buenos_Aires',
    latitude: -34.6037,
    longitude: -58.3816,
  },
  {
    label: 'Lima',
    region: 'Peru',
    timezone: 'America/Lima',
    latitude: -12.0464,
    longitude: -77.0428,
  },
  {
    label: 'Santiago',
    region: 'Chile',
    timezone: 'America/Santiago',
    latitude: -33.4489,
    longitude: -70.6693,
  },
  {
    label: 'São Paulo',
    region: 'Brazil',
    timezone: 'America/Sao_Paulo',
    latitude: -23.5505,
    longitude: -46.6333,
  },
];
